# Generated by Django 3.1.5 on 2021-01-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['-id']},
        ),
    ]
