# Generated by Django 3.1.5 on 2021-01-29 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('medicines', '0002_medicine_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='address',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=255)),
                ('works_from', models.TimeField(blank=True)),
                ('works_to', models.TimeField(blank=True)),
                ('works_day_and_night', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacies', to='regions.district')),
            ],
        ),
    ]
