# Generated by Django 3.1.5 on 2021-01-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_auto_20210129_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='works_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='works_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
