# Generated by Django 3.1.5 on 2021-01-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_auto_20210129_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(choices=[('TABLET', 'tablet'), ('SYRUP', 'syrup'), ('CAPSULE', 'capsule'), ('OTHER', 'other')], default='OTHER', max_length=15),
        ),
    ]
