# Generated by Django 3.1.5 on 2021-02-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_medicine_medicine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('SYRUP', 'Syrup'), ('CAPSULE', 'Capsule'), ('OTHER', 'Other')], default='OTHER', max_length=15),
        ),
    ]
