# Generated by Django 3.1.5 on 2021-02-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0009_medicine_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacymedicine',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
